import '../styles/globals.css'
import Head from 'next/head'
import Navbar from '@/components/Navbar/Navbar';

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar></Navbar>
      <Component {...pageProps} />
    </>
  );
}
